# Generated by Django 2.0 on 2019-05-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190514_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(upload_to='logo/', verbose_name='logo'),
        ),
    ]
