# Generated by Django 2.0 on 2017-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171208_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=150, verbose_name="nom d'équipe"),
        ),
    ]
