# Generated by Django 2.0 on 2019-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190514_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamachievement',
            name='picture',
            field=models.CharField(default='default.jpg', max_length=150, verbose_name='nom de la photo'),
        ),
    ]
