# Generated by Django 2.0 on 2019-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_teamachievement_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamachievement',
            name='picture',
            field=models.CharField(default='default', max_length=150, verbose_name='nom de la photo'),
        ),
    ]
