# Generated by Django 2.0 on 2017-12-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171209_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, verbose_name='numéro de série')),
                ('valid', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balises', to='api.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='team',
        ),
        migrations.AddField(
            model_name='position',
            name='dh',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='nom constaté'),
        ),
        migrations.AddField(
            model_name='position',
            name='balise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Balise'),
        ),
    ]
