# Generated by Django 2.0 on 2017-12-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171209_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='balise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.Balise'),
        ),
    ]
