# Generated by Django 2.0 on 2017-12-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171209_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='distance',
            field=models.IntegerField(default=0, help_text='en mètres', verbose_name='distance parcourue'),
        ),
    ]
