# Generated by Django 2.0 on 2017-12-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
