# Generated by Django 2.0 on 2017-12-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_team_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
